// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"spark/internal/models"
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AIReply struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Tone string `json:"tone"`
}

type AIReplyResponse struct {
	Replies        []*AIReply `json:"replies"`
	RemainingToday int32      `json:"remaining_today"`
}

type AIUsageStatus struct {
	CanUse         bool       `json:"can_use"`
	RemainingToday int32      `json:"remaining_today"`
	ResetsAt       *time.Time `json:"resets_at,omitempty"`
}

type AddressInput struct {
	City    string `json:"city"`
	State   string `json:"state"`
	Country string `json:"country"`
}

type AdminReport struct {
	ID             string     `json:"id"`
	UserID         string     `json:"user_id"`
	Reporter       *AdminUser `json:"reporter,omitempty"`
	TargetID       string     `json:"target_id"`
	Target         *AdminUser `json:"target,omitempty"`
	Reason         string     `json:"reason"`
	AdditionalInfo *string    `json:"additional_info,omitempty"`
	Media          []string   `json:"media,omitempty"`
	Status         string     `json:"status"`
	CreatedAt      time.Time  `json:"created_at"`
}

type AdminStats struct {
	TotalUsers           int32                  `json:"total_users"`
	ActiveUsersToday     int32                  `json:"active_users_today"`
	ActiveUsersWeek      int32                  `json:"active_users_week"`
	TotalMatches         int32                  `json:"total_matches"`
	MatchesToday         int32                  `json:"matches_today"`
	TotalMessages        int32                  `json:"total_messages"`
	MessagesToday        int32                  `json:"messages_today"`
	PendingVerifications int32                  `json:"pending_verifications"`
	PendingReports       int32                  `json:"pending_reports"`
	TotalSubscribers     int32                  `json:"total_subscribers"`
	SubscribersByPlan    []*PlanSubscriberCount `json:"subscribers_by_plan"`
	RevenueThisMonth     int32                  `json:"revenue_this_month"`
}

type AdminUser struct {
	ID                 string     `json:"id"`
	FirstName          string     `json:"first_name"`
	LastName           string     `json:"last_name"`
	Email              string     `json:"email"`
	Pfp                *string    `json:"pfp,omitempty"`
	Gender             *string    `json:"gender,omitempty"`
	IsVerified         bool       `json:"is_verified"`
	IsBanned           bool       `json:"is_banned"`
	Role               string     `json:"role"`
	SubscriptionPlanID *string    `json:"subscription_plan_id,omitempty"`
	CreatedAt          time.Time  `json:"created_at"`
	LastActive         *time.Time `json:"last_active,omitempty"`
}

type AdminUserFilters struct {
	Search             *string    `json:"search,omitempty"`
	IsVerified         *bool      `json:"is_verified,omitempty"`
	IsBanned           *bool      `json:"is_banned,omitempty"`
	Role               *string    `json:"role,omitempty"`
	SubscriptionPlanID *string    `json:"subscription_plan_id,omitempty"`
	CreatedAfter       *time.Time `json:"created_after,omitempty"`
	CreatedBefore      *time.Time `json:"created_before,omitempty"`
}

type AdminUserList struct {
	Users   []*AdminUser `json:"users"`
	Total   int32        `json:"total"`
	Page    int32        `json:"page"`
	PerPage int32        `json:"per_page"`
}

type AdminVerification struct {
	ID        string     `json:"id"`
	UserID    string     `json:"user_id"`
	User      *AdminUser `json:"user,omitempty"`
	Media     []string   `json:"media"`
	Status    string     `json:"status"`
	CreatedAt time.Time  `json:"created_at"`
}

// Return value after successful auth
type AuthPayload struct {
	AccessToken string       `json:"access_token"`
	User        *models.User `json:"user"`
}

type BlockedUser struct {
	ID            string    `json:"id"`
	UserID        string    `json:"user_id"`
	BlockedUserID string    `json:"blocked_user_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type CheckoutSession struct {
	CheckoutURL string `json:"checkout_url"`
	SessionID   string `json:"session_id"`
	Provider    string `json:"provider"`
}

type CommentFilterInput struct {
	PostID        *string    `json:"post_id,omitempty"`
	UserID        *string    `json:"user_id,omitempty"`
	ReplyToID     *string    `json:"reply_to_id,omitempty"`
	ParentOnly    *bool      `json:"parent_only,omitempty"`
	SearchContent *string    `json:"search_content,omitempty"`
	CreatedAfter  *time.Time `json:"created_after,omitempty"`
	CreatedBefore *time.Time `json:"created_before,omitempty"`
	MinLikes      *int32     `json:"min_likes,omitempty"`
}

type CommentsConnection struct {
	Comments   []*models.Comment `json:"comments"`
	PageInfo   *PageInfo         `json:"page_info"`
	TotalCount int32             `json:"total_count"`
}

type Connection struct {
	Chat               *models.Chat  `json:"chat"`
	Match              *models.Match `json:"match"`
	LastMessage        string        `json:"last_message"`
	UnreadMessages     int32         `json:"unread_messages"`
	PercentageComplete float64       `json:"percentage_complete"`
	ConnectionProfile  *UserPublic   `json:"connection_profile"`
}

type CreateCommentInput struct {
	PostID    string  `json:"post_id"`
	ReplyToID *string `json:"reply_to_id,omitempty"`
	Content   string  `json:"content"`
}

type CreatePostInput struct {
	Content string        `json:"content"`
	Media   []*MediaInput `json:"media,omitempty"`
}

type CreateReportInput struct {
	TargetID       string        `json:"target_id"`
	Reason         string        `json:"reason"`
	AdditionalInfo *string       `json:"additional_info,omitempty"`
	Media          []*MediaInput `json:"media"`
}

type CreateUserInput struct {
	Email       string        `json:"email"`
	Password    string        `json:"password"`
	FirstName   string        `json:"first_name"`
	LastName    string        `json:"last_name"`
	Dob         time.Time     `json:"dob"`
	Gender      string        `json:"gender"`
	Pfp         *string       `json:"pfp,omitempty"`
	Bio         *string       `json:"bio,omitempty"`
	Hobbies     []string      `json:"hobbies,omitempty"`
	Interests   []string      `json:"interests,omitempty"`
	UserPrompts []string      `json:"user_prompts,omitempty"`
	Photos      []string      `json:"photos,omitempty"`
	Address     *AddressInput `json:"address,omitempty"`
}

type ExtraMetadataInput struct {
	School     *string  `json:"school,omitempty"`
	Work       *string  `json:"work,omitempty"`
	LookingFor []string `json:"looking_for,omitempty"`
	Zodiac     *string  `json:"zodiac,omitempty"`
	Languages  []string `json:"languages,omitempty"`
	Excercise  *string  `json:"excercise,omitempty"`
	Drinking   *string  `json:"drinking,omitempty"`
	Smoking    *string  `json:"smoking,omitempty"`
	Kids       *string  `json:"kids,omitempty"`
	Religion   *string  `json:"religion,omitempty"`
	Ethnicity  *string  `json:"ethnicity,omitempty"`
	Sexuality  *string  `json:"sexuality,omitempty"`
}

type GenerateAIRepliesInput struct {
	ChatID          string  `json:"chat_id"`
	ContextMessages *int32  `json:"context_messages,omitempty"`
	Tone            *string `json:"tone,omitempty"`
}

type MassNotificationInput struct {
	Title   string   `json:"title"`
	Body    string   `json:"body"`
	Segment *string  `json:"segment,omitempty"`
	UserIds []string `json:"user_ids,omitempty"`
}

type MassNotificationResult struct {
	Success     bool    `json:"success"`
	SentCount   int32   `json:"sent_count"`
	FailedCount int32   `json:"failed_count"`
	Message     *string `json:"message,omitempty"`
}

type MediaInput struct {
	ID        string    `json:"id"`
	URL       string    `json:"url"`
	Type      MediaType `json:"type"`
	CreatedAt string    `json:"created_at"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"has_next_page"`
	NextCursor      *string `json:"next_cursor,omitempty"`
	HasPreviousPage bool    `json:"has_previous_page"`
	PreviousCursor  *string `json:"previous_cursor,omitempty"`
}

type PersonalityTrait struct {
	Key   string `json:"key"`
	Value int32  `json:"value"`
}

type PersonalityTraitInput struct {
	Key   string `json:"key"`
	Value int32  `json:"value"`
}

type PlanSubscriberCount struct {
	PlanID   string `json:"plan_id"`
	PlanName string `json:"plan_name"`
	Count    int32  `json:"count"`
}

type PostFilterInput struct {
	UserID        *string    `json:"user_id,omitempty"`
	SearchContent *string    `json:"search_content,omitempty"`
	CreatedAfter  *time.Time `json:"created_after,omitempty"`
	CreatedBefore *time.Time `json:"created_before,omitempty"`
	MinLikes      *int32     `json:"min_likes,omitempty"`
	MinComments   *int32     `json:"min_comments,omitempty"`
	MinViews      *int32     `json:"min_views,omitempty"`
	HasMedia      *bool      `json:"has_media,omitempty"`
}

type PostsConnection struct {
	Posts      []*models.Post `json:"posts"`
	PageInfo   *PageInfo      `json:"page_info"`
	TotalCount int32          `json:"total_count"`
}

type PushNotificationResult struct {
	Success bool    `json:"success"`
	Message *string `json:"message,omitempty"`
}

type Query struct {
}

type RecommendationFilter struct {
	Gender        *string  `json:"gender,omitempty"`
	MinAge        *int32   `json:"min_age,omitempty"`
	MaxAge        *int32   `json:"max_age,omitempty"`
	MaxDistanceKm *float64 `json:"max_distance_km,omitempty"`
	VerifiedOnly  *bool    `json:"verified_only,omitempty"`
}

type RecommendationsResult struct {
	Items      []*RecommendedProfile `json:"items"`
	NextCursor *string               `json:"next_cursor,omitempty"`
	HasMore    bool                  `json:"has_more"`
	FetchedAt  time.Time             `json:"fetched_at"`
}

type RecommendedProfile struct {
	Profile            *UserPublic `json:"profile"`
	MatchScore         float64     `json:"match_score"`
	CompatibilityScore float64     `json:"compatibility_score"`
	CommonInterests    []string    `json:"common_interests"`
	DistanceKm         *float64    `json:"distance_km,omitempty"`
	Reason             *string     `json:"reason,omitempty"`
}

type RegisterPushTokenInput struct {
	Token    string  `json:"token"`
	Platform string  `json:"platform"`
	DeviceID *string `json:"device_id,omitempty"`
}

type SortInput struct {
	Field string    `json:"field"`
	Order SortOrder `json:"order"`
}

type StreakMilestone struct {
	Days       int32      `json:"days"`
	Emoji      string     `json:"emoji"`
	Title      string     `json:"title"`
	AchievedAt *time.Time `json:"achieved_at,omitempty"`
}

type SwipeResponse struct {
	Swipe *models.Swipe `json:"swipe"`
	Match *models.Match `json:"match,omitempty"`
}

type SwipedProfile struct {
	Profile *UserPublic   `json:"profile"`
	Swipe   *models.Swipe `json:"swipe"`
}

type UpdateCommentInput struct {
	CommentID string `json:"comment_id"`
	Content   string `json:"content"`
}

type UpdatePostInput struct {
	PostID  string        `json:"post_id"`
	Content *string       `json:"content,omitempty"`
	Media   []*MediaInput `json:"media,omitempty"`
}

type UpdateUserInput struct {
	FirstName         *string                  `json:"first_name,omitempty"`
	LastName          *string                  `json:"last_name,omitempty"`
	Dob               *time.Time               `json:"dob,omitempty"`
	Pfp               *string                  `json:"pfp,omitempty"`
	Bio               *string                  `json:"bio,omitempty"`
	Gender            *string                  `json:"gender,omitempty"`
	Hobbies           []string                 `json:"hobbies,omitempty"`
	Interests         []string                 `json:"interests,omitempty"`
	UserPrompts       []string                 `json:"user_prompts,omitempty"`
	PersonalityTraits []*PersonalityTraitInput `json:"personality_traits,omitempty"`
	Photos            []string                 `json:"photos,omitempty"`
	IsVerified        *bool                    `json:"is_verified,omitempty"`
	Address           *AddressInput            `json:"address,omitempty"`
	Extra             *ExtraMetadataInput      `json:"extra,omitempty"`
}

type UserPublic struct {
	ID                string                `json:"id"`
	Name              string                `json:"name"`
	Pfp               string                `json:"pfp"`
	Bio               string                `json:"bio"`
	Dob               string                `json:"dob"`
	Gender            string                `json:"gender"`
	Hobbies           []string              `json:"hobbies"`
	Interests         []string              `json:"interests"`
	UserPrompts       []string              `json:"user_prompts"`
	PersonalityTraits []*PersonalityTrait   `json:"personality_traits"`
	Photos            []string              `json:"photos"`
	IsVerified        bool                  `json:"is_verified"`
	Extra             *models.ExtraMetadata `json:"extra,omitempty"`
	CreatedAt         time.Time             `json:"created_at"`
	IsOnline          bool                  `json:"is_online"`
	IsLocked          bool                  `json:"is_locked"`
	IsPoked           bool                  `json:"is_poked"`
	ChatID            string                `json:"chat_id"`
}

type UserStreakStats struct {
	TotalActiveStreaks int32              `json:"total_active_streaks"`
	LongestStreakEver  int32              `json:"longest_streak_ever"`
	CurrentMilestones  []*StreakMilestone `json:"current_milestones"`
}

type UserSubscriptionStatus struct {
	PlanID             string                       `json:"plan_id"`
	Plan               *models.SubscriptionPlan     `json:"plan"`
	IsSubscribed       bool                         `json:"is_subscribed"`
	Subscription       *models.UserSubscription     `json:"subscription,omitempty"`
	Limits             *models.SubscriptionLimits   `json:"limits"`
	Features           *models.SubscriptionFeatures `json:"features"`
	SwipesRemaining    int32                        `json:"swipes_remaining"`
	AiRepliesRemaining int32                        `json:"ai_replies_remaining"`
}

type UserVerificationInput struct {
	Media []*MediaInput `json:"media"`
}

type ActivityClass string

const (
	ActivityClassReceived ActivityClass = "RECEIVED"
	ActivityClassSent     ActivityClass = "SENT"
	ActivityClassAll      ActivityClass = "ALL"
)

var AllActivityClass = []ActivityClass{
	ActivityClassReceived,
	ActivityClassSent,
	ActivityClassAll,
}

func (e ActivityClass) IsValid() bool {
	switch e {
	case ActivityClassReceived, ActivityClassSent, ActivityClassAll:
		return true
	}
	return false
}

func (e ActivityClass) String() string {
	return string(e)
}

func (e *ActivityClass) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActivityClass(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActivityClass", str)
	}
	return nil
}

func (e ActivityClass) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActivityClass) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActivityClass) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentSortField string

const (
	CommentSortFieldCreatedAt CommentSortField = "CREATED_AT"
	CommentSortFieldLikes     CommentSortField = "LIKES"
)

var AllCommentSortField = []CommentSortField{
	CommentSortFieldCreatedAt,
	CommentSortFieldLikes,
}

func (e CommentSortField) IsValid() bool {
	switch e {
	case CommentSortFieldCreatedAt, CommentSortFieldLikes:
		return true
	}
	return false
}

func (e CommentSortField) String() string {
	return string(e)
}

func (e *CommentSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentSortField", str)
	}
	return nil
}

func (e CommentSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MediaType string

const (
	MediaTypeImage MediaType = "IMAGE"
	MediaTypeVideo MediaType = "VIDEO"
	MediaTypeAudio MediaType = "AUDIO"
	MediaTypeFile  MediaType = "FILE"
)

var AllMediaType = []MediaType{
	MediaTypeImage,
	MediaTypeVideo,
	MediaTypeAudio,
	MediaTypeFile,
}

func (e MediaType) IsValid() bool {
	switch e {
	case MediaTypeImage, MediaTypeVideo, MediaTypeAudio, MediaTypeFile:
		return true
	}
	return false
}

func (e MediaType) String() string {
	return string(e)
}

func (e *MediaType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MediaType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MediaType", str)
	}
	return nil
}

func (e MediaType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MediaType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MediaType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PostSortField string

const (
	PostSortFieldCreatedAt PostSortField = "CREATED_AT"
	PostSortFieldLikes     PostSortField = "LIKES"
	PostSortFieldComments  PostSortField = "COMMENTS"
	PostSortFieldViews     PostSortField = "VIEWS"
)

var AllPostSortField = []PostSortField{
	PostSortFieldCreatedAt,
	PostSortFieldLikes,
	PostSortFieldComments,
	PostSortFieldViews,
}

func (e PostSortField) IsValid() bool {
	switch e {
	case PostSortFieldCreatedAt, PostSortFieldLikes, PostSortFieldComments, PostSortFieldViews:
		return true
	}
	return false
}

func (e PostSortField) String() string {
	return string(e)
}

func (e *PostSortField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostSortField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostSortField", str)
	}
	return nil
}

func (e PostSortField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PostSortField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PostSortField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SortOrder string

const (
	SortOrderAsc  SortOrder = "ASC"
	SortOrderDesc SortOrder = "DESC"
)

var AllSortOrder = []SortOrder{
	SortOrderAsc,
	SortOrderDesc,
}

func (e SortOrder) IsValid() bool {
	switch e {
	case SortOrderAsc, SortOrderDesc:
		return true
	}
	return false
}

func (e SortOrder) String() string {
	return string(e)
}

func (e *SortOrder) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortOrder(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortOrder", str)
	}
	return nil
}

func (e SortOrder) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SortOrder) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SortOrder) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
