package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	ai "spark/internal/helpers/ai"
	"spark/internal/helpers/subscriptions"
	"spark/internal/graph/directives"
	"spark/internal/graph/model"
	"context"
	"fmt"
	"time"
)

// GenerateAIReplies is the resolver for the generateAIReplies field.
func (r *mutationResolver) GenerateAIReplies(ctx context.Context, input model.GenerateAIRepliesInput) (*model.AIReplyResponse, error) {
	claims, _, err := directives.GetAuthClaims(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized")
	}

	contextMessages := 10
	if input.ContextMessages != nil {
		contextMessages = int(*input.ContextMessages)
	}

	tone := ""
	if input.Tone != nil {
		tone = *input.Tone
	}

	result, err := ai.GenerateAIReplies(claims.UserID, input.ChatID, contextMessages, tone)
	if err != nil {
		return &model.AIReplyResponse{
			Replies:        []*model.AIReply{},
			RemainingToday: 0,
		}, err
	}

	// Convert to GraphQL model
	replies := make([]*model.AIReply, len(result.Replies))
	for i, reply := range result.Replies {
		replies[i] = &model.AIReply{
			ID:   reply.ID,
			Text: reply.Text,
			Tone: string(reply.Tone),
		}
	}

	return &model.AIReplyResponse{
		Replies:        replies,
		RemainingToday: int32(result.RemainingToday),
	}, nil
}

// AiUsageStatus is the resolver for the aiUsageStatus field.
func (r *queryResolver) AiUsageStatus(ctx context.Context) (*model.AIUsageStatus, error) {
	claims, _, err := directives.GetAuthClaims(ctx)
	if err != nil {
		return nil, fmt.Errorf("unauthorized")
	}

	canUse, remaining, err := subscriptions.CanUseAIReplies(claims.UserID)
	if err != nil {
		return nil, err
	}

	// Calculate reset time (next midnight)
	now := time.Now()
	tomorrow := time.Date(now.Year(), now.Month(), now.Day()+1, 0, 0, 0, 0, now.Location())

	return &model.AIUsageStatus{
		CanUse:         canUse,
		RemainingToday: int32(remaining),
		ResetsAt:       &tomorrow,
	}, nil
}
