package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/graph/model"
	"context"
)

// BlockUser is the resolver for the blockUser field.
func (r *mutationResolver) BlockUser(ctx context.Context, userID string) (bool, error) {
	return r.BlockedUsersResolver.BlockUser(ctx, userID)
}

// UnblockUser is the resolver for the unblockUser field.
func (r *mutationResolver) UnblockUser(ctx context.Context, userID string) (bool, error) {
	return r.BlockedUsersResolver.UnblockUser(ctx, userID)
}

// BlockedUsers is the resolver for the blockedUsers field.
func (r *queryResolver) BlockedUsers(ctx context.Context) ([]*model.UserPublic, error) {
	return r.BlockedUsersResolver.BlockedUsers(ctx)
}

// IsUserBlocked is the resolver for the isUserBlocked field.
func (r *queryResolver) IsUserBlocked(ctx context.Context, userID string) (bool, error) {
	return r.BlockedUsersResolver.IsUserBlocked(ctx, userID)
}
