package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/graph/model"
	"spark/internal/models"
	"context"
	"fmt"
)

// Score is the resolver for the score field.
func (r *matchResolver) Score(ctx context.Context, obj *models.Match) (int32, error) {
	if obj == nil {
		return 0, fmt.Errorf("match is nil")
	}
	return int32(obj.Score), nil
}

// SheRating is the resolver for the she_rating field.
func (r *postUnlockRatingResolver) SheRating(ctx context.Context, obj *models.PostUnlockRating) (int32, error) {
	if obj == nil {
		return 0, fmt.Errorf("post unlock rating is nil")
	}
	return int32(obj.SheRating), nil
}

// HeRating is the resolver for the he_rating field.
func (r *postUnlockRatingResolver) HeRating(ctx context.Context, obj *models.PostUnlockRating) (int32, error) {
	if obj == nil {
		return 0, fmt.Errorf("post unlock rating is nil")
	}
	return int32(obj.HeRating), nil
}

// GetMyConnections is the resolver for the getMyConnections field.
func (r *queryResolver) GetMyConnections(ctx context.Context) ([]*model.Connection, error) {
	return r.ChatsResolver.GetMyConnections(ctx)
}

// Match returns MatchResolver implementation.
func (r *Resolver) Match() MatchResolver { return &matchResolver{r} }

// PostUnlockRating returns PostUnlockRatingResolver implementation.
func (r *Resolver) PostUnlockRating() PostUnlockRatingResolver { return &postUnlockRatingResolver{r} }

type matchResolver struct{ *Resolver }
type postUnlockRatingResolver struct{ *Resolver }
