package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/anal"
	"spark/internal/graph/directives"
	"spark/internal/graph/model"
	"spark/internal/helpers/users"
	"spark/internal/models"
	"context"
	"fmt"
)

// Likes is the resolver for the likes field.
func (r *commentResolver) Likes(ctx context.Context, obj *models.Comment) (int32, error) {
	if obj == nil {
		return 0, fmt.Errorf("comment is nil")
	}
	return int32(obj.Likes), nil
}

// User is the resolver for the user field.
func (r *commentResolver) User(ctx context.Context, obj *models.Comment) (*model.UserPublic, error) {
	claims, ae, err := directives.GetAuthClaims(ctx)
	if err != nil {
		ae.SendRequestError(anal.UNAUTHORIZED_401, err)
		return nil, fmt.Errorf("unauthorized: %w", err)
	}
	if obj == nil {
		return nil, fmt.Errorf("comment is nil")
	}
	user, err := users.GetUserPublicById(obj.UserId, claims.UserID)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Type is the resolver for the type field.
func (r *mediaResolver) Type(ctx context.Context, obj *models.Media) (model.MediaType, error) {
	if obj == nil {
		return model.MediaTypeImage, fmt.Errorf("media is nil")
	}
	return model.MediaType(obj.Type), nil
}

// CreatePost is the resolver for the create_post field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*models.Post, error) {
	return r.CommunityResolver.CreatePost(ctx, input)
}

// UpdatePost is the resolver for the update_post field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (*models.Post, error) {
	return r.CommunityResolver.UpdatePost(ctx, input)
}

// DeletePost is the resolver for the delete_post field.
func (r *mutationResolver) DeletePost(ctx context.Context, postID string) (bool, error) {
	return r.CommunityResolver.DeletePost(ctx, postID)
}

// CreateComment is the resolver for the create_comment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*models.Comment, error) {
	return r.CommunityResolver.CreateComment(ctx, input)
}

// UpdateComment is the resolver for the update_comment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input model.UpdateCommentInput) (*models.Comment, error) {
	return r.CommunityResolver.UpdateComment(ctx, input)
}

// DeleteComment is the resolver for the delete_comment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, commentID string) (bool, error) {
	return r.CommunityResolver.DeleteComment(ctx, commentID)
}

// TogglePostLike is the resolver for the toggle_post_like field.
func (r *mutationResolver) TogglePostLike(ctx context.Context, postID string) (*models.Post, error) {
	return r.CommunityResolver.TogglePostLike(ctx, postID)
}

// ToggleCommentLike is the resolver for the toggle_comment_like field.
func (r *mutationResolver) ToggleCommentLike(ctx context.Context, commentID string) (*models.Comment, error) {
	return r.CommunityResolver.ToggleCommentLike(ctx, commentID)
}

// IncrementPostView is the resolver for the increment_post_view field.
func (r *mutationResolver) IncrementPostView(ctx context.Context, postID string) (*models.Post, error) {
	return r.CommunityResolver.IncrementPostView(ctx, postID)
}

// Likes is the resolver for the likes field.
func (r *postResolver) Likes(ctx context.Context, obj *models.Post) (int32, error) {
	if obj == nil {
		return 0, nil
	}
	return int32(obj.Likes), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *models.Post) (int32, error) {
	if obj == nil {
		return 0, nil
	}
	return int32(obj.Comments), nil
}

// Views is the resolver for the views field.
func (r *postResolver) Views(ctx context.Context, obj *models.Post) (int32, error) {
	if obj == nil {
		return 0, nil
	}
	return int32(obj.Views), nil
}

// User is the resolver for the user field.
func (r *postResolver) User(ctx context.Context, obj *models.Post) (*model.UserPublic, error) {
	claims, ae, err := directives.GetAuthClaims(ctx)
	if err != nil {
		ae.SendRequestError(anal.UNAUTHORIZED_401, err)
		return nil, fmt.Errorf("unauthorized: %w", err)
	}
	if obj == nil {
		return nil, fmt.Errorf("post is nil")
	}
	user, err := users.GetUserPublicById(obj.UserId, claims.UserID)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// GetPosts is the resolver for the get_posts field.
func (r *queryResolver) GetPosts(ctx context.Context, filter *model.PostFilterInput, sort *model.SortInput, limit *int32, cursor *string) (*model.PostsConnection, error) {
	return r.CommunityResolver.GetPosts(ctx, filter, sort, limit, cursor)
}

// GetPost is the resolver for the get_post field.
func (r *queryResolver) GetPost(ctx context.Context, postID string) (*models.Post, error) {
	return r.CommunityResolver.GetPost(ctx, postID)
}

// GetFeedPosts is the resolver for the get_feed_posts field.
func (r *queryResolver) GetFeedPosts(ctx context.Context, limit *int32, cursor *string) (*model.PostsConnection, error) {
	return r.CommunityResolver.GetFeedPosts(ctx, limit, cursor)
}

// GetComments is the resolver for the get_comments field.
func (r *queryResolver) GetComments(ctx context.Context, filter model.CommentFilterInput, sort *model.SortInput, limit *int32, cursor *string) (*model.CommentsConnection, error) {
	return r.CommunityResolver.GetComments(ctx, filter, sort, limit, cursor)
}

// GetComment is the resolver for the get_comment field.
func (r *queryResolver) GetComment(ctx context.Context, commentID string) (*models.Comment, error) {
	return r.CommunityResolver.GetComment(ctx, commentID)
}

// GetTrendingPosts is the resolver for the get_trending_posts field.
func (r *queryResolver) GetTrendingPosts(ctx context.Context, timeWindow *int32, limit *int32, cursor *string) (*model.PostsConnection, error) {
	return r.CommunityResolver.GetTrendingPosts(ctx, timeWindow, limit, cursor)
}

// Comment returns CommentResolver implementation.
func (r *Resolver) Comment() CommentResolver { return &commentResolver{r} }

// Media returns MediaResolver implementation.
func (r *Resolver) Media() MediaResolver { return &mediaResolver{r} }

// Post returns PostResolver implementation.
func (r *Resolver) Post() PostResolver { return &postResolver{r} }

type commentResolver struct{ *Resolver }
type mediaResolver struct{ *Resolver }
type postResolver struct{ *Resolver }
