package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/graph/directives"
	"spark/internal/graph/model"
	"spark/internal/helpers/pushnotify"
	"context"
	"fmt"
)

// RegisterPushToken is the resolver for the registerPushToken field.
func (r *mutationResolver) RegisterPushToken(ctx context.Context, input model.RegisterPushTokenInput) (*model.PushNotificationResult, error) {
	claims, _, err := directives.GetAuthClaims(ctx)
	if err != nil {
		return &model.PushNotificationResult{
			Success: false,
			Message: strPtr("Unauthorized"),
		}, nil
	}

	deviceID := ""
	if input.DeviceID != nil {
		deviceID = *input.DeviceID
	}

	if err := pushnotify.RegisterToken(claims.UserID, input.Token, input.Platform, deviceID); err != nil {
		return &model.PushNotificationResult{
			Success: false,
			Message: strPtr(fmt.Sprintf("Failed to register token: %v", err)),
		}, nil
	}

	return &model.PushNotificationResult{
		Success: true,
		Message: strPtr("Token registered successfully"),
	}, nil
}

// RemovePushToken is the resolver for the removePushToken field.
func (r *mutationResolver) RemovePushToken(ctx context.Context, token string) (*model.PushNotificationResult, error) {
	_, _, err := directives.GetAuthClaims(ctx)
	if err != nil {
		return &model.PushNotificationResult{
			Success: false,
			Message: strPtr("Unauthorized"),
		}, nil
	}

	if err := pushnotify.RemoveToken(token); err != nil {
		return &model.PushNotificationResult{
			Success: false,
			Message: strPtr(fmt.Sprintf("Failed to remove token: %v", err)),
		}, nil
	}

	return &model.PushNotificationResult{
		Success: true,
		Message: strPtr("Token removed successfully"),
	}, nil
}

// Helper function for string pointers
func strPtr(s string) *string {
	return &s
}
