package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/anal"
	"spark/internal/graph/directives"
	"spark/internal/graph/model"
	"spark/internal/helpers/users"
	"spark/internal/models"
	"context"
	"fmt"
)

// CreateProfileActivity is the resolver for the createProfileActivity field.
func (r *mutationResolver) CreateProfileActivity(ctx context.Context, typeArg models.ActivityType, targetUserID string) (*models.UserProfileActivity, error) {
	return r.ProfileActivityResolver.CreateProfileActivity(ctx, typeArg, targetUserID)
}

// ProfileActivities is the resolver for the profileActivities field.
func (r *queryResolver) ProfileActivities(ctx context.Context, class *model.ActivityClass) ([]*models.UserProfileActivity, error) {
	return r.ProfileActivityResolver.ProfileActivities(ctx, class)
}

// TargetUser is the resolver for the target_user field.
func (r *userProfileActivityResolver) TargetUser(ctx context.Context, obj *models.UserProfileActivity) (*model.UserPublic, error) {
	claims, ae, err := directives.GetAuthClaims(ctx)
	if err != nil {
		ae.SendRequestError(anal.UNAUTHORIZED_401, err)
		return nil, fmt.Errorf("unauthorized: %w", err)
	}
	if claims.UserID == obj.TargetId {
		return users.GetUserPublicById(obj.UserId, claims.UserID)
	}
	return users.GetUserPublicById(obj.TargetId, claims.UserID)
}

// Class is the resolver for the class field.
func (r *userProfileActivityResolver) Class(ctx context.Context, obj *models.UserProfileActivity) (model.ActivityClass, error) {
	claims, ae, err := directives.GetAuthClaims(ctx)
	if err != nil {
		ae.SendRequestError(anal.UNAUTHORIZED_401, err)
		return model.ActivityClassAll, fmt.Errorf("unauthorized: %w", err)
	}
	if obj == nil {
		return model.ActivityClassAll, nil
	} else {
		if claims.UserID == obj.TargetId {
			return model.ActivityClassReceived, nil
		}
		return model.ActivityClassSent, nil
	}
}

// UserProfileActivity returns UserProfileActivityResolver implementation.
func (r *Resolver) UserProfileActivity() UserProfileActivityResolver {
	return &userProfileActivityResolver{r}
}

type userProfileActivityResolver struct{ *Resolver }
