package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/graph/model"
	"spark/internal/models"
	"context"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.AuthPayload, error) {
	return r.UserResolver.CreateUser(ctx, input)
}

// LoginWithPassword is the resolver for the loginWithPassword field.
func (r *mutationResolver) LoginWithPassword(ctx context.Context, email string, password string) (*model.AuthPayload, error) {
	return r.UserResolver.LoginWithPassword(ctx, email, password)
}

// RequestEmailLoginCode is the resolver for the requestEmailLoginCode field.
func (r *mutationResolver) RequestEmailLoginCode(ctx context.Context, email string) (bool, error) {
	return r.UserResolver.RequestEmailLoginCode(ctx, email)
}

// VerifyEmailLoginCode is the resolver for the verifyEmailLoginCode field.
func (r *mutationResolver) VerifyEmailLoginCode(ctx context.Context, email string, code string) (*model.AuthPayload, error) {
	return r.UserResolver.VerifyEmailLoginCode(ctx, email, code)
}

// UpdateMe is the resolver for the updateMe field.
func (r *mutationResolver) UpdateMe(ctx context.Context, input model.UpdateUserInput) (*models.User, error) {
	return r.UserResolver.UpdateMe(ctx, input)
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthPayload, error) {
	return r.UserResolver.RefreshToken(ctx)
}

// RequestAccountDeletion is the resolver for the requestAccountDeletion field.
func (r *mutationResolver) RequestAccountDeletion(ctx context.Context) (bool, error) {
	return r.UserResolver.RequestAccountDeletion(ctx)
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, confirmationCode string) (bool, error) {
	return r.UserResolver.DeleteAccount(ctx, confirmationCode)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*models.User, error) {
	return r.UserResolver.Me(ctx)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.UserPublic, error) {
	return r.UserResolver.User(ctx, id)
}

// PersonalityTraits is the resolver for the personality_traits field.
func (r *userResolver) PersonalityTraits(ctx context.Context, obj *models.User) ([]*model.PersonalityTrait, error) {
	var traits []*model.PersonalityTrait
	if obj != nil {
		for k, v := range obj.PersonalityTraits {
			traits = append(traits, &model.PersonalityTrait{
				Key:   k,
				Value: int32(v),
			})
		}
	}
	return traits, nil
}

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
