package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"spark/internal/graph/model"
	"spark/internal/models"
	"context"
)

// CreateVerification is the resolver for the createVerification field.
func (r *mutationResolver) CreateVerification(ctx context.Context, input model.UserVerificationInput) (*models.UserVerification, error) {
	return r.VerificationResolver.CreateVerification(ctx, input)
}

// GetUserVerificationStatus is the resolver for the getUserVerificationStatus field.
func (r *queryResolver) GetUserVerificationStatus(ctx context.Context) (*models.UserVerification, error) {
	return r.VerificationResolver.GetUserVerificationStatus(ctx)
}
